FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN sed -i -e "s|archive.ubuntu.com|mirrors.hit.edu.cn|g" -e "s|security.ubuntu.com|mirrors.hit.edu.cn|g" /etc/apt/sources.list
RUN apt-get update && apt-get install -y zip unzip build-essential
COPY judger/uoj_judger /opt/uoj/judger/uoj_judger
RUN cd /opt/uoj/judger/uoj_judger && make -j$(($(nproc) + 1))
